import type { Metadata } from 'next';
import './globals.css';
import CommonLayout from '@/components/common-layout';
import { Footer, Navbar } from '@/components';

export const metadata: Metadata = {
  title: 'Shopping Cart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar />
        <CommonLayout>{children}</CommonLayout>
        <Footer />
      </body>
    </html>
  );
}
